# Change to your own name
site_name: My Research Page
# Change to your own site
site_url: https://steob92.github.io/mcgill-tutorial/ # must have the trailing slash
site_author: Your Name (stephan.obrien@mcgill.ca)
site_description: Research site for Your Name 
copyright: > # should remain a link to the original theme
  &copy; 2023 Your Name <br>
  <a href="https://github.com/vuquangtrong/mkdocs-material-blog">Blog Theme</a> /
  <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>



theme:
    name: material
    palette:
      # Palette toggle for light mode
      - scheme: default
        # Color of the top bar
        primary: deep purple
        # Link highlight color
        accent : orange
        
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

    features:
    - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level sections are shown as tabs
    - navigation.tabs.sticky # tabs always show
    - navigation.sections # sections are rendered as groups in the sidebar
    - navigation.expand # all sections are expanded
    - navigation.indexes # link an index.md page to a section
    - navigation.top # show back-to-top button
    - toc.integrate # show table of contents to navigation panel
    - header.autohide
    - content.code.annotate 
    - content.code.copy

extra_javascript:
  
  # For rendering latex
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# For describing the navigation panel
nav:
  - Home: index.md
  - About Me: about/index.md
  - Research: reasearch/index.md
  - Projects: projects/index.md

# Extensions that we want to use
markdown_extensions:
  - attr_list   # For adding attributes such as right/left align to images
  - md_in_html  # Using Figures



# Additional plugins
plugins:
    - search
    # Using jupyter notebook  
    - mkdocs-jupyter:
          theme: default

